export interface SwitchgearProduct {
  id: string
  name: string
  category: string
  description: string
  specifications: {
    voltage?: string
    amperage: string[]
    poles?: string
    breakingCapacity?: string
    standard?: string
    packQty?: number
    features?: string[]
  }
  pricing: {
    [key: string]: number
  }
  image?: string
}

export const switchgearCategories = [
  "MCB",
  "Isolator",
  "Distribution Board",
  "Fuse Kit-Kat",
  "Switch Fuse Unit",
  "Control Switches",
  "Change Over Switches",
  "RCCB/ELCB",
  "MCCB",
  "RCBO",
] as const

export const switchgearProducts: SwitchgearProduct[] = [
  // MCB 'B' & 'C' Series Products (keeping these as they are different from the ones to be deleted)
  {
    id: "mcb-b-c-sp",
    name: "MCB 'B' & 'C' Series SP (Single Pole)",
    category: "MCB",
    description: "ISI Marked 240/415V Miniature Circuit Breaker with 10KA breaking capacity",
    image: "/images/products/mcb-b-c-series-sp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Single Pole",
      breakingCapacity: "10KA",
      standard: "ISI Mark Approved",
      packQty: 300,
      features: ["B & C Type Tripping", "High Short Circuit Capacity", "Arc Extinguish System", "IP20 Protection"],
    },
    pricing: {
      "0.5-5A": 180,
      "6-32A": 140,
      "40A": 170,
      "63A": 240,
    },
  },
  {
    id: "mcb-b-c-spn",
    name: "MCB 'B' & 'C' Series SPN (Single Pole Neutral)",
    category: "MCB",
    description: "ISI Marked 240/415V Single Pole Neutral MCB with 10KA breaking capacity",
    image: "/images/products/mcb-b-c-spn.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Single Pole Neutral",
      breakingCapacity: "10KA",
      standard: "ISI Mark Approved",
      packQty: 150,
      features: ["B & C Type Tripping", "Neutral Protection", "Compact Design"],
    },
    pricing: {
      "0.5-5A": 530,
      "6-32A": 350,
      "40A": 470,
      "63A": 605,
    },
  },
  {
    id: "mcb-b-c-dp",
    name: "MCB 'B' & 'C' Series DP (Double Pole)",
    category: "MCB",
    description: "ISI Marked 240/415V Double Pole MCB with 10KA breaking capacity",
    image: "/images/products/mcb-dp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Double Pole",
      breakingCapacity: "10KA",
      standard: "ISI Mark Approved",
      packQty: 150,
      features: ["Simultaneous Tripping", "Both Phase Protection", "Reliable Operation"],
    },
    pricing: {
      "0.5-5A": 585,
      "6-32A": 385,
      "40A": 515,
      "63A": 640,
    },
  },
  {
    id: "mcb-c-tp",
    name: "MCB 'C' Series TP (Triple Pole)",
    category: "MCB",
    description: "ISI Marked 240/415V Triple Pole MCB with 10KA breaking capacity",
    image: "/images/products/mcb-c-series-tp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Triple Pole",
      breakingCapacity: "10KA",
      standard: "ISI Mark Approved",
      packQty: 100,
      features: ["Three Phase Protection", "C Type Tripping Curve", "Industrial Applications"],
    },
    pricing: {
      "0.5-5A": 870,
      "6-32A": 605,
      "40A": 770,
      "63A": 890,
    },
  },
  {
    id: "mcb-c-tpn",
    name: "MCB 'C' Series TPN (Triple Pole Neutral)",
    category: "MCB",
    description: "ISI Marked 240/415V Triple Pole Neutral MCB with 10KA breaking capacity",
    image: "/images/products/mcb-c-series-tpn.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Triple Pole Neutral",
      breakingCapacity: "10KA",
      standard: "ISI Mark Approved",
      packQty: 75,
      features: ["Three Phase + Neutral", "Complete Protection", "Commercial Applications"],
    },
    pricing: {
      "0.5-5A": 1055,
      "6-32A": 850,
      "40A": 1045,
      "63A": 1210,
    },
  },
  {
    id: "mcb-c-fp",
    name: "MCB 'C' Series FP (Four Pole)",
    category: "MCB",
    description: "ISI Marked 240/415V Four Pole MCB with 10KA breaking capacity",
    image: "/images/products/mcb-fp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Four Pole",
      breakingCapacity: "10KA",
      standard: "ISI Mark Approved",
      packQty: 75,
      features: ["Four Pole Protection", "Maximum Safety", "Industrial Grade"],
    },
    pricing: {
      "0.5-5A": 1265,
      "6-32A": 960,
      "40A": 1185,
      "63A": 1485,
    },
  },

  // MCB DC Series
  {
    id: "mcb-dc-sp",
    name: "MCB DC Series - Single Pole",
    category: "MCB",
    description: "DC MCB suitable for DC voltages up to 220V DC",
    image: "/images/products/mcb-dc-series-single-pole.png",
    specifications: {
      voltage: "220V DC",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Single Pole",
      standard: "IEC 60898-2",
      packQty: 300,
      features: ["DC Applications", "High Performance", "Reliable Operation"],
    },
    pricing: {
      "0.5-5A": 350,
      "6-32A": 310,
      "40A": 450,
      "63A": 550,
    },
  },
  {
    id: "mcb-dc-dp",
    name: "MCB DC Series - Double Pole",
    category: "MCB",
    description: "DC MCB Double Pole suitable for DC voltages up to 220V DC",
    image: "/images/products/mcb-dc-dp.png",
    specifications: {
      voltage: "220V DC",
      amperage: ["0.5-5A", "6-32A", "40A", "63A"],
      poles: "Double Pole",
      standard: "IEC 60898-2",
      packQty: 150,
      features: ["DC Applications", "Double Pole Protection", "Industrial Grade"],
    },
    pricing: {
      "0.5-5A": 980,
      "6-32A": 740,
      "40A": 1090,
      "63A": 1190,
    },
  },

  // Mini MCB
  {
    id: "mini-mcb-sp",
    name: "Mini MCB SP (Single Pole) 'C' Series",
    category: "MCB",
    description: "Compact Mini MCB for space-constrained applications",
    image: "/images/products/mini-mcb-sp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["6-32A", "40A"],
      poles: "Single Pole",
      standard: "C Series",
      packQty: 300,
      features: ["Compact Design", "Space Saving", "High Performance"],
    },
    pricing: {
      "6-32A": 125,
      "40A": 195,
    },
  },
  {
    id: "mini-mcb-dp-enclosure",
    name: "Mini MCB DP Enclosure (Double Pole) 'C' Series",
    category: "MCB",
    description: "Mini MCB Double Pole with enclosure",
    image: "/images/products/mini-mcb-dp-enclosure.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["6-32A", "40A"],
      poles: "Double Pole",
      standard: "C Series",
      packQty: 150,
      features: ["With Enclosure", "Double Pole Protection", "Compact"],
    },
    pricing: {
      "6-32A": 395,
      "40A": 515,
    },
  },

  // Change Over Switches Category
  {
    id: "mcb-changeover-2way",
    name: "Two Way Centre Off MCB Changeover Switch",
    category: "Change Over Switches",
    description: "Two Way Centre Off MCB Changeover Switch as per IS/IEC 60947-3",
    image: "/images/products/two-way-centre-off-mcb-changeover.png",
    specifications: {
      voltage: "415V",
      amperage: ["25A", "40A", "63A"],
      poles: "Double Pole",
      standard: "IS/IEC 60947-3",
      packQty: 150,
      features: ["Centre Off Position", "Manual Operation", "Reliable Switching"],
    },
    pricing: {
      "25A": 485,
      "40A": 660,
      "63A": 880,
    },
  },
  {
    id: "mcb-changeover-4way",
    name: "Four Way Centre Off MCB Changeover Switch",
    category: "Change Over Switches",
    description: "Four Way Centre Off MCB Changeover Switch as per IS/IEC 60947-3",
    image: "/images/products/four-way-centre-off-mcb-changeover.png",
    specifications: {
      voltage: "415V",
      amperage: ["25A", "40A", "63A"],
      poles: "Four Pole",
      standard: "IS/IEC 60947-3",
      packQty: 75,
      features: ["Four Pole Switching", "Centre Off Position", "Industrial Applications"],
    },
    pricing: {
      "25A": 1090,
      "40A": 1450,
      "63A": 1705,
    },
  },
  {
    id: "changeover-switch-dp",
    name: "Change Over Switch (Double Pole)",
    category: "Change Over Switches",
    description: "Change Over Switch Double Pole as per IS/IEC 60947-3 with various voltage and amperage options",
    image: "/images/products/changeover-switch-double-pole.png",
    specifications: {
      voltage: "240V/415V",
      amperage: ["16A", "32A", "63A"],
      poles: "Double Pole",
      standard: "IS/IEC 60947-3",
      packQty: 20,
      features: ["Manual Operation", "Double Pole Switching", "Reliable Performance", "Multiple Voltage Options"],
    },
    pricing: {
      "16A-240V": 1080,
      "32A-240V": 1680,
      "16A-415V": 1800,
      "32A-415V": 1990,
      "63A-415V": 4740,
    },
  },
  {
    id: "changeover-switch-u-type-fp",
    name: "Change Over Switch (U Type) Four Pole",
    category: "Change Over Switches",
    description: "Change Over Switch U Type Four Pole as per IS/IEC 60947-3 for industrial applications",
    image: "/images/products/changeover-switch-u-type-four-pole.png",
    specifications: {
      voltage: "415V",
      amperage: ["16A", "32A", "63A", "100A", "200A"],
      poles: "Four Pole",
      standard: "IS/IEC 60947-3",
      packQty: 10,
      features: ["U Type Design", "Four Pole Operation", "Heavy Duty Construction", "Industrial Grade"],
    },
    pricing: {
      "16A": 2620,
      "32A": 5480,
      "63A": 6220,
      "100A": 11990,
      "200A": 19990,
    },
  },
  {
    id: "changeover-switch-knife-type-fp",
    name: "Change Over Switch (Knife Type) Four Pole",
    category: "Change Over Switches",
    description: "Change Over Switch Knife Type Four Pole as per IS/IEC 60947-3 for heavy duty applications",
    image: "/images/products/changeover-switch-knife-type-four-pole.png",
    specifications: {
      voltage: "415V",
      amperage: ["63A", "100A", "200A", "320A", "400A", "500A", "630A", "800A", "1000A"],
      poles: "Four Pole",
      standard: "IS/IEC 60947-3",
      packQty: 2,
      features: ["Knife Type Design", "Four Pole Switching", "Industrial Grade", "High Current Capacity"],
    },
    pricing: {
      "63A": 9290,
      "100A": 11950,
      "200A": 22950,
      "320A": 26250,
      "400A": 35850,
      "500A": 44190,
      "630A": 64350,
      "800A": 75250,
      "1000A": 89950,
    },
  },
  {
    id: "switch-cum-changeover-tp",
    name: "Switch Cum Change Over Three Pole",
    category: "Change Over Switches",
    description: "Switch Cum Change Over Three Pole as per IS/IEC 60947-3 with combined switching functionality",
    image: "/images/products/switch-cum-changeover-three-pole.png",
    specifications: {
      voltage: "415V",
      amperage: ["32A", "63A", "100A"],
      poles: "Three Pole",
      standard: "IS/IEC 60947-3",
      packQty: 6,
      features: ["Switch + Changeover Function", "Three Pole Operation", "Versatile Design", "Industrial Applications"],
    },
    pricing: {
      "32A": 8990,
      "63A": 7800,
      "100A": 14090,
    },
  },
  {
    id: "automatic-changeover-dp-tp-fp",
    name: "Automatic Change Over Switch - DP,TP & FP",
    category: "Change Over Switches",
    description:
      "Automatic Change Over Switch available in Double Pole, Triple Pole & Four Pole configurations as per IS/IEC 60947-3",
    image: "/images/products/automatic-changeover-switch.png",
    specifications: {
      voltage: "415V",
      amperage: ["25A", "40A", "63A", "100A"],
      poles: "DP/TP/FP",
      standard: "IS/IEC 60947-3",
      packQty: 50,
      features: [
        "Automatic Operation",
        "Multiple Pole Options",
        "Reliable Switching",
        "Industrial Grade",
        "Emergency Backup",
      ],
    },
    pricing: {
      "25A-DP": 2850,
      "40A-DP": 3250,
      "63A-DP": 3650,
      "100A-DP": 4850,
      "25A-TP": 3850,
      "40A-TP": 4250,
      "63A-TP": 4650,
      "100A-TP": 5850,
      "25A-FP": 4850,
      "40A-FP": 5250,
      "63A-FP": 5650,
      "100A-FP": 6850,
    },
  },

  // Isolator Products (keeping the main ones, removing the specific ones mentioned)
  {
    id: "isolator-dp",
    name: "Isolator DP MCB (Double Pole)",
    category: "Isolator",
    description: "Double Pole Isolator MCB as per IS: 60947-3, 240/415V, 50Hz",
    image: "/images/products/isolator-dp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["40A", "63A", "100A"],
      poles: "Double Pole",
      standard: "As per IS Standards",
      packQty: 150,
      features: ["Safe Isolation", "Manual Operation", "Visible Contact Gap"],
    },
    pricing: {
      "40A": 285,
      "63A": 360,
      "100A": 525,
    },
  },
  {
    id: "isolator-tp",
    name: "Isolator TP MCB (Triple Pole)",
    category: "Isolator",
    description: "Triple Pole Isolator MCB as per IS: 60947-3, 240/415V, 50Hz",
    image: "/images/products/isolator-tp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["40A", "63A", "100A"],
      poles: "Triple Pole",
      standard: "As per IS Standards",
      packQty: 100,
      features: ["Three Phase Isolation", "Lockable Handle", "Maintenance Safety"],
    },
    pricing: {
      "40A": 495,
      "63A": 580,
      "100A": 800,
    },
  },
  {
    id: "isolator-fp",
    name: "Isolator FP MCB (Four Pole)",
    category: "Isolator",
    description: "Four Pole Isolator MCB as per IS: 60947-3, 240/415V, 50Hz",
    image: "/images/products/isolator-fp.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["40A", "63A", "100A"],
      poles: "Four Pole",
      standard: "As per IS Standards",
      packQty: 75,
      features: ["Complete Isolation", "Four Pole Safety", "Industrial Applications"],
    },
    pricing: {
      "40A": 605,
      "63A": 680,
      "100A": 1090,
    },
  },

  // Distribution Board Products
  {
    id: "mcb-enclosure-plastic",
    name: "Plastic MCB Enclosures with DIN Channel",
    category: "Distribution Board",
    description: "Single Phase plastic MCB enclosures without neutral link",
    image: "/images/products/plastic-mcb-enclosure-din.png",
    specifications: {
      voltage: "240V",
      amperage: ["1/2 Pole", "3/4 Pole"],
      features: ["DIN Channel", "Plastic Construction", "Surface Mounting"],
    },
    pricing: {
      "1/2 Pole": 120,
      "3/4 Pole": 220,
    },
  },
  {
    id: "mcb-enclosure-metal",
    name: "Sheet Metal MCB Enclosure",
    category: "Distribution Board",
    description: "Single Phase sheet metal MCB enclosures with neutral link",
    image: "/images/products/steel-mcb-enclosure.png",
    specifications: {
      voltage: "240V",
      amperage: ["1/2 Pole", "3/4 Pole"],
      features: ["With Neutral Link", "Metal Construction", "Durable"],
    },
    pricing: {
      "1/2 Pole": 400,
      "3/4 Pole": 590,
    },
  },
  {
    id: "db-spn-single-door",
    name: "Single Phase (SPN) Distribution Board - Single Door",
    category: "Distribution Board",
    description: "Single Phase Distribution Board as per IS: 13032 with single door",
    image: "/images/products/spn-distribution-board-single-door.png",
    specifications: {
      voltage: "240V",
      amperage: ["4 Way", "6 Way", "8 Way", "10 Way", "12 Way", "16 Way"],
      standard: "IS: 13032",
      features: ["Surface Mounting", "Earth Link", "Powder Coating", "Detachable Top & Bottom"],
    },
    pricing: {
      "4 Way": 675,
      "6 Way": 790,
      "8 Way": 950,
      "10 Way": 1090,
      "12 Way": 1280,
      "16 Way": 1490,
    },
  },
  {
    id: "db-tpn-single-door",
    name: "Three Phase (TPN) Distribution Board - Single Door",
    category: "Distribution Board",
    description: "Three Phase Distribution Board as per IS: 13032 with single door",
    image: "/images/products/tpn-distribution-board-single-door.png",
    specifications: {
      voltage: "415V",
      amperage: ["4 Way", "6 Way", "8 Way", "10 Way", "12 Way"],
      standard: "IS: 13032",
      features: ["Three Phase Distribution", "Robust Construction", "Industrial Grade"],
    },
    pricing: {
      "4 Way": 2365,
      "6 Way": 2990,
      "8 Way": 3560,
      "10 Way": 4620,
      "12 Way": 4940,
    },
  },
  {
    id: "db-spn-double-door",
    name: "Single Phase (SPN) Distribution Board - Double Door",
    category: "Distribution Board",
    description: "Single Phase Distribution Board as per IS: 13032 with double door",
    image: "/images/products/spn-distribution-board-double-door.png",
    specifications: {
      voltage: "240V",
      amperage: ["4 Way", "6 Way", "8 Way", "10 Way", "12 Way", "16 Way"],
      standard: "IS: 13032",
      features: ["Double Door", "Easy Access", "Professional Grade"],
    },
    pricing: {
      "4 Way": 990,
      "6 Way": 1280,
      "8 Way": 1590,
      "10 Way": 1790,
      "12 Way": 1990,
      "16 Way": 2390,
    },
  },
  {
    id: "db-tpn-double-door",
    name: "Three Phase (TPN) Distribution Board - Double Door",
    category: "Distribution Board",
    description: "Three Phase Distribution Board as per IS: 13032 with double door",
    image: "/images/products/tpn-distribution-board-double-door.png",
    specifications: {
      voltage: "415V",
      amperage: ["4 Way", "6 Way", "8 Way", "10 Way", "12 Way"],
      standard: "IS: 13032",
      features: ["Double Door Access", "Three Phase", "Heavy Duty"],
    },
    pricing: {
      "4 Way": 2590,
      "6 Way": 3290,
      "8 Way": 3980,
      "10 Way": 5190,
      "12 Way": 5670,
    },
  },
  {
    id: "db-spn-transparent",
    name: "Single Phase (SPN) Transparent Cover Distribution Board",
    category: "Distribution Board",
    description: "Single Phase Distribution Board with transparent cover (White Line)",
    image: "/images/products/tpn-distribution-board-transparent.png",
    specifications: {
      voltage: "240V",
      amperage: ["4 Way", "6 Way", "8 Way", "10 Way", "12 Way", "16 Way"],
      standard: "IS: 13032",
      features: ["Transparent Cover", "White Line Series", "Visual Access"],
    },
    pricing: {
      "4 Way": 990,
      "6 Way": 1280,
      "8 Way": 1590,
      "10 Way": 1790,
      "12 Way": 1990,
      "16 Way": 2390,
    },
  },
  {
    id: "plug-socket-board",
    name: "Plug & Socket Boards (SP & TP)",
    category: "Distribution Board",
    description: "Plug & Socket Boards in AC Box for single and three phase",
    image: "/images/products/plug-socket-board-sp-tp.png",
    specifications: {
      voltage: "250V/440V",
      amperage: ["1P+20A,250V (SP)", "3P+20A,440V (TP)", "3P+30A,440V (TP)"],
      features: ["AC Box", "Industrial Grade", "Weather Resistant"],
    },
    pricing: {
      "1P+20A,250V (SP)": 780,
      "3P+20A,440V (TP)": 1880,
      "3P+30A,440V (TP)": 2890,
    },
  },
  {
    id: "plug-open-metal",
    name: "Plug Open (SP & TP) in Metal Sheet Enclosure",
    category: "Distribution Board",
    description: "Plug Open in metal sheet enclosure for single and three phase",
    image: "/images/products/plug-open-metal-enclosure.png",
    specifications: {
      voltage: "250V/440V",
      amperage: ["2P+E 20A, 250V", "3P+E 20A, 440V", "3P+E 30A, 440V"],
      features: ["Metal Sheet Enclosure", "Earth Connection", "Durable Construction"],
    },
    pricing: {
      "2P+E 20A, 250V": 290,
      "3P+E 20A, 440V": 360,
      "3P+E 30A, 440V": 880,
    },
  },
  {
    id: "socket-open",
    name: "Socket Open (SP & TP)",
    category: "Distribution Board",
    description: "Socket Open for single and three phase applications",
    image: "/images/products/socket-open-sp-tp.png",
    specifications: {
      voltage: "250V/440V",
      amperage: ["2P+E 20A, 250V", "3P+E 20A, 440V", "3P+E 30A, 440V"],
      features: ["Open Type", "Earth Connection", "Industrial Applications"],
    },
    pricing: {
      "2P+E 20A, 250V": 350,
      "3P+E 20A, 440V": 450,
      "3P+E 30A, 440V": 960,
    },
  },

  // Porcelain Fuse Kit-Kat
  {
    id: "porcelain-fuse-kitkat",
    name: "Porcelain Fuse Kit-Kat",
    category: "Fuse Kit-Kat",
    description: "Porcelain Fuse Kit-Kat for various voltage and current ratings",
    image: "/images/products/porcelain-fuse-kitkat.png",
    specifications: {
      voltage: "240V/415V",
      amperage: [
        "16A-240V",
        "32A-240V",
        "32A-415V",
        "63A-415V",
        "100A-415V",
        "200A-415V",
        "320A-415V",
        "400A-415V",
        "500A-415V",
      ],
      features: ["Porcelain Construction", "High Breaking Capacity", "Reliable Protection"],
    },
    pricing: {
      "16A-240V": 105,
      "32A-240V": 205,
      "32A-415V": 290,
      "63A-415V": 620,
      "100A-415V": 1060,
      "200A-415V": 1860,
      "320A-415V": 2650,
      "400A-415V": 3360,
      "500A-415V": 3990,
    },
  },
  {
    id: "porcelain-fuse-kitkat-extension",
    name: "Porcelain Fuse Kit-Kat (With Extension Patti)",
    category: "Fuse Kit-Kat",
    description: "Porcelain Fuse Kit-Kat with extension patti for enhanced connectivity",
    image: "/images/products/porcelain-fuse-kitkat-extension.png",
    specifications: {
      voltage: "415V",
      amperage: ["63A", "100A", "200A", "320A", "400A", "500A"],
      features: ["With Extension Patti", "Enhanced Connectivity", "Professional Grade"],
    },
    pricing: {
      "63A": 775,
      "100A": 1250,
      "200A": 2330,
      "320A": 3360,
      "400A": 4190,
      "500A": 4950,
    },
  },

  // Switch Fuse Unit Products
  {
    id: "sfu-sp",
    name: "Switch Fuse Unit - Single Pole",
    category: "Switch Fuse Unit",
    description: "Re-wireable Switch Fuse Unit as per IS: 60947 with ISI Mark",
    image: "/images/products/switch-fuse-unit-single-pole.png",
    specifications: {
      voltage: "240V/415V",
      amperage: ["16A-240V", "32A-240V", "16A-415V", "32A-415V", "63A-415V", "100A-415V"],
      poles: "Single Pole",
      standard: "ISI Mark Approved",
      features: ["Re-wireable Fuses", "Manual Operation", "Overload Protection"],
    },
    pricing: {
      "16A-240V": 690,
      "32A-240V": 1390,
      "16A-415V": 1450,
      "32A-415V": 1900,
      "63A-415V": 4190,
      "100A-415V": 8600,
    },
  },
  {
    id: "sfu-dp",
    name: "Switch Fuse Unit - Double Pole",
    category: "Switch Fuse Unit",
    description: "Re-wireable Switch Fuse Unit as per IS: 60947 with ISI Mark",
    image: "/images/products/switch-fuse-unit-double-pole.png",
    specifications: {
      voltage: "240V/415V",
      amperage: ["16A-240V", "32A-240V", "16A-415V", "32A-415V", "63A-415V"],
      poles: "Double Pole",
      standard: "ISI Mark Approved",
      features: ["Double Pole Protection", "Simultaneous Operation", "Reliable Switching"],
    },
    pricing: {
      "16A-240V": 750,
      "32A-240V": 1450,
      "16A-415V": 1490,
      "32A-415V": 1950,
      "63A-415V": 4290,
      "100A-415V": 8750,
    },
  },
  {
    id: "sfu-tp",
    name: "Switch Fuse Unit - Triple Pole",
    category: "Switch Fuse Unit",
    description: "Re-wireable Switch Fuse Unit as per IS: 60947 with ISI Mark",
    image: "/images/products/switch-fuse-unit-triple-pole.png",
    specifications: {
      voltage: "415V",
      amperage: ["16A", "32A", "63A", "100A", "200A", "320A"],
      poles: "Triple Pole",
      standard: "ISI Mark Approved",
      features: ["Three Phase Protection", "Industrial Applications", "Heavy Duty Construction"],
    },
    pricing: {
      "16A": 1790,
      "32A": 2190,
      "63A": 5590,
      "100A": 9990,
      "200A": 14990,
      "320A": 20900,
    },
  },
  {
    id: "sfu-tpn",
    name: "Switch Fuse Unit - Triple Pole Neutral",
    category: "Switch Fuse Unit",
    description: "Re-wireable Switch Fuse Unit as per IS: 60947 with ISI Mark",
    image: "/images/products/switch-fuse-unit-triple-pole-neutral.png",
    specifications: {
      voltage: "415V",
      amperage: ["16A", "32A", "63A", "100A", "200A", "320A", "400A", "500A"],
      poles: "Triple Pole Neutral",
      standard: "ISI Mark Approved",
      features: ["Three Phase + Neutral", "Complete Protection", "Industrial Grade"],
    },
    pricing: {
      "16A": 1880,
      "32A": 2390,
      "63A": 5890,
      "100A": 10490,
      "200A": 15850,
      "320A": 22900,
      "400A": 27950,
      "500A": 38900,
    },
  },
  {
    id: "double-break-fuse-switch",
    name: "Double Break Fuse Switch (Without HRC Fuses)",
    category: "Switch Fuse Unit",
    description: "Double Break Fuse Switch as per IS: 60947 AC-23A without HRC fuses",
    image: "/images/products/double-break-fuse-switch-without-hrc.png",
    specifications: {
      voltage: "415V",
      amperage: ["63A", "100A", "200A", "320A", "400A", "500A", "630A"],
      standard: "IS: 60947 AC-23A",
      features: ["Double Break", "Without HRC Fuses", "High Performance"],
    },
    pricing: {
      "63A": 9690,
      "100A": 12200,
      "200A": 18600,
      "320A": 21700,
      "400A": 32050,
      "500A": 40490,
      "630A": 63900,
    },
  },
  {
    id: "double-break-fuse-switch-hrc",
    name: "Double Break Fuse Switch (With HRC Fuses)",
    category: "Switch Fuse Unit",
    description: "Double Break Fuse Switch as per IS: 60947 AC-23A with HRC fuses",
    image: "/images/products/double-break-fuse-switch-hrc.png",
    specifications: {
      voltage: "415V",
      amperage: ["63A", "100A", "200A", "320A", "400A", "500A", "630A"],
      standard: "IS: 60947 AC-23A",
      features: ["Double Break", "With HRC Fuses", "Enhanced Protection"],
    },
    pricing: {
      "63A": 9990,
      "100A": 12890,
      "200A": 20850,
      "320A": 24750,
      "400A": 34400,
      "500A": 44950,
      "630A": 73900,
    },
  },

  // L.T. Control Switches
  {
    id: "lt-control-switches",
    name: "L.T. Control Change Over & Reverse-Forward (With Enclosure)",
    category: "Control Switches",
    description: "L.T. Control switches with enclosure for various applications",
    image: "/images/products/lt-control-switch.png",
    specifications: {
      voltage: "415V",
      amperage: ["2P-16A", "3P-16A", "2P-32A", "3P-32A", "4P-32A", "3P-16A (REV.-FOR.)", "3P-32A (REV.-FOR.)"],
      features: ["With Enclosure", "Change Over", "Reverse-Forward Options"],
    },
    pricing: {
      "2P-16A": 1100,
      "3P-16A": 1250,
      "2P-32A": 1560,
      "3P-32A": 1875,
      "4P-32A": 2190,
      "3P-16A (REV.-FOR.)": 1100,
      "3P-32A (REV.-FOR.)": 1650,
    },
  },
  {
    id: "bus-bar-chamber-tin-plated",
    name: "Bus Bar Chamber (With Tin Plated Copper Strip)",
    category: "Control Switches",
    description: "Bus Bar Chamber with tin plated copper strip for enhanced conductivity",
    image: "/images/products/bus-bar-chamber.png",
    specifications: {
      voltage: "415V",
      amperage: ["16A", "32A", "63A", "100A", "200A", "320A", "400A", "500A", "630A", "1000A"],
      features: ["Tin Plated Copper Strip", "Various Sizes", "Professional Grade"],
    },
    pricing: {
      "16A": 1990,
      "32A": 2150,
      "63A": 4590,
      "100A": 6980,
      "200A": 8930,
      "320A": 17250,
      "400A": 21750,
      "500A": 24900,
      "630A": 32650,
      "1000A": 54550,
    },
  },
  {
    id: "by-pass-switches-open-execution",
    name: "By Pass Switches - Open Execution",
    category: "Control Switches",
    description: "By Pass Switches for maintenance and service applications - Open Execution",
    image: "/images/products/by-pass-switches-open.png",
    specifications: {
      voltage: "415V",
      amperage: ["100A", "125A", "160A", "200A", "250A", "320A", "400A", "630A"],
      features: ["By Pass Operation", "Open Execution", "Maintenance Applications"],
    },
    pricing: {
      "100A": 34500,
      "125A": 37900,
      "160A": 44850,
      "200A": 48550,
      "250A": 67270,
      "320A": 70550,
      "400A": 110550,
      "630A": 119990,
    },
  },
  {
    id: "switch-fuse-disconnector-open",
    name: "Switch Fuse Disconnector (SDF) - Open Execution",
    category: "Control Switches",
    description: "Front Operated Cubical Type Switch Disconnector Fuse (Triple Pole Neutral) - Open Execution",
    image: "/images/products/switch-fuse-disconnector-open.png",
    specifications: {
      voltage: "415V",
      amperage: ["32A", "63A", "100A", "125A", "160A", "200A", "250A", "315A", "400A", "630A"],
      poles: "Triple Pole Neutral",
      features: ["Front Operated", "Cubical Type", "Without HRC Fuse"],
    },
    pricing: {
      "32A": 2975,
      "63A": 4180,
      "100A": 8800,
      "125A": 9900,
      "160A": 12975,
      "200A": 15850,
      "250A": 18500,
      "315A": 24900,
      "400A": 28600,
      "630A": 49500,
    },
  },
  {
    id: "switch-fuse-disconnector-enclosure",
    name: "Switch Fuse Disconnector (SDF) - With Sheet Steel Enclosure",
    category: "Control Switches",
    description:
      "Front Operated Cubical Type Switch Disconnector Fuse (Triple Pole Neutral) - With Sheet Steel Enclosure",
    image: "/images/products/switch-fuse-disconnector-enclosure.png",
    specifications: {
      voltage: "415V",
      amperage: ["32A", "63A", "100A", "125A", "160A", "200A", "250A", "315A", "400A", "630A"],
      poles: "Triple Pole Neutral",
      features: ["Front Operated", "Sheet Steel Enclosure", "Without HRC Fuses"],
    },
    pricing: {
      "32A": 5950,
      "63A": 8170,
      "100A": 13800,
      "125A": 15900,
      "160A": 18950,
      "200A": 21550,
      "250A": 24000,
      "315A": 29950,
      "400A": 38900,
      "630A": 59500,
    },
  },
  {
    id: "load-break-switch-open",
    name: "Load Break Switches FP - Open Execution",
    category: "Control Switches",
    description: "Load Break Switches FP (Four Pole) 100A-1000A, 415V, 50Hz - Open Execution",
    image: "/images/products/load-break-switch-open.png",
    specifications: {
      voltage: "415V",
      amperage: ["63A", "80A", "100A", "125A", "160A", "200A", "250A", "320A", "400A", "630A", "800A", "1000A"],
      poles: "Four Pole",
      features: ["Load Break Operation", "Open Execution", "High Performance"],
    },
    pricing: {
      "63A": 4290,
      "80A": 5250,
      "100A": 8500,
      "125A": 8990,
      "160A": 14950,
      "200A": 16800,
      "250A": 19750,
      "320A": 21670,
      "400A": 29500,
      "630A": 31900,
      "800A": 42850,
      "1000A": 74000,
    },
  },
  {
    id: "load-break-switch-enclosure",
    name: "Load Break Switches FP - With Sheet Steel Enclosure",
    category: "Control Switches",
    description: "Load Break Switches FP (Four Pole) 100A-1000A, 415V, 50Hz - With Sheet Steel Enclosure",
    image: "/images/products/load-break-switch-enclosure.png",
    specifications: {
      voltage: "415V",
      amperage: ["63A", "80A", "100A", "125A", "160A", "200A", "250A", "320A", "400A", "630A", "800A", "1000A"],
      poles: "Four Pole",
      features: ["Load Break Operation", "Sheet Steel Enclosure", "Weather Protection"],
    },
    pricing: {
      "63A": 7150,
      "80A": 9160,
      "100A": 13500,
      "125A": 14900,
      "160A": 20200,
      "200A": 29950,
      "250A": 34500,
      "320A": 38000,
      "400A": 42500,
      "630A": 55250,
      "800A": 69580,
      "1000A": 99550,
    },
  },

  // RCCB/ELCB Products
  {
    id: "rccb-dp",
    name: "RCCB/ELCB - Double Pole",
    category: "RCCB/ELCB",
    description: "Residual Current Circuit Breaker as per IS: 12640-1-2000",
    image: "/images/products/rccb-elcb-double-pole.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["25A", "40A", "63A", "100A"],
      poles: "Double Pole",
      standard: "As per IS Standards",
      features: ["Earth Leakage Protection", "30mA/100mA/300mA Sensitivity", "10KA Short Circuit Capacity"],
    },
    pricing: {
      "25A-30mA": 2140,
      "40A-30mA": 2350,
      "63A-30mA": 2790,
      "25A-100mA": 2090,
      "40A-100mA": 2300,
      "63A-100mA": 2750,
      "25A-300mA": 2250,
      "40A-300mA": 2500,
      "63A-300mA": 2990,
      "100A": 5450,
    },
  },
  {
    id: "rccb-fp",
    name: "RCCB/ELCB - Four Pole",
    category: "RCCB/ELCB",
    description: "Four Pole Residual Current Circuit Breaker as per IS: 12640-1-2000",
    image: "/images/products/rccb-elcb-four-pole.png",
    specifications: {
      voltage: "240/415V",
      amperage: ["25A", "40A", "63A", "100A"],
      poles: "Four Pole",
      standard: "As per IS Standards",
      features: ["Four Pole Protection", "Comprehensive Safety", "Industrial Applications"],
    },
    pricing: {
      "25A": 3650,
      "40A": 3850,
      "63A": 4150,
    },
  },
]
